[manager]
prepend_keymap = [
    { on = "i", run = 'leave' },
    { on = "n", run = 'enter' },
    { on = "u", run = 'arrow -1' },
    { on = "p", run = 'arrow 1' },
    { on = "<a-i>", run = 'back' },
    { on = "<a-n>", run = 'forward' },

    { on = "a", run = 'open' },
    { on = "<c-f7>", run = 'open --interactive' },

    { on = "e", run = 'plugin smart-filter' },
    { on = "<a-e>", run = 'find --smart' },
    { on = "<c-e>", run = 'filter --smart' },
    { on = "t", run = 'find_arrow' },
    { on = "r", run = 'find_arrow --previous' },
    { on = "<a-s>", run = 'search rg' },
    { on = "<c-f20>", run = 'escape --search' },


    { on = "l", run = 'rename --cursor=before_ext' },
    { on = "b", run = 'create' },


    { on = "c", run = 'yank' },
    { on = "<a-c>", run = 'yank --cut' },

    { on = "h", run = 'paste' },
    { on = "<a-h>", run = 'paste --force' },

    { on = "y", run = 'link' },
    { on = "<a-y>", run = 'link --relative' },
    { on = "d", run = 'hardlink' },

    { on = "m", run = 'remove' },
    { on = "f", run = 'plugin jump-to-char' },


    { on = "Escape", run = 'close' },

    { on = "o", run = 'shell "powershell.exe" --block --confirm' },
    { on = "v", run = 'shell --interactive' },

    { on = [ "j", "m" ], run = [ "sort modified --reverse=no", "linemode mtime" ], desc = "Sort by modified time" },
	{ on = [ "j", "M" ], run = [ "sort modified --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
	{ on = [ "j", "c" ], run = [ "sort created --reverse=no", "linemode ctime" ],  desc = "Sort by created time" },
	{ on = [ "j", "C" ], run = [ "sort created --reverse", "linemode ctime" ],     desc = "Sort by created time (reverse)" },
	{ on = [ "j", "e" ], run = "sort extension --reverse=no",                      desc = "Sort by extension" },
	{ on = [ "j", "E" ], run = "sort extension --reverse",                         desc = "Sort by extension (reverse)" },
	{ on = [ "j", "a" ], run = "sort alphabetical --reverse=no",                   desc = "Sort alphabetically" },
	{ on = [ "j", "A" ], run = "sort alphabetical --reverse",                      desc = "Sort alphabetically (reverse)" },
	{ on = [ "j", "n" ], run = "sort natural --reverse=no",                        desc = "Sort naturally" },
	{ on = [ "j", "N" ], run = "sort natural --reverse",                           desc = "Sort naturally (reverse)" },
	{ on = [ "j", "s" ], run = [ "sort size --reverse=no", "linemode size" ],      desc = "Sort by size" },
	{ on = [ "j", "S" ], run = [ "sort size --reverse", "linemode size" ],         desc = "Sort by size (reverse)" },
	{ on = [ "j", "r" ], run = "sort random --reverse=no",                         desc = "Sort randomly" },

    { on = [ "k", "c" ], run = "copy path",             desc = "Copy the file path" },
	{ on = [ "k", "d" ], run = "copy dirname",          desc = "Copy the directory path" },
	{ on = [ "k", "f" ], run = "copy filename",         desc = "Copy the filename" },
	{ on = [ "k", "n" ], run = "copy name_without_ext", desc = "Copy the filename without extension" },

]
